let replace_single_quote input_string =
  String.map (fun c -> if c = '\'' then '"' else c) input_string

let replace_double_quote input_string =
  String.map (fun c -> if c = '"' then '\'' else c) input_string

let expected_values =
  [
    (* (Program name, amount of branches, JSON)*)
    ("programs/spai2.py", 12, "{'trace':{'return':{'Tconst':[{'sources':[],'sinks':[]},0]},'state':{'svm':{'operator':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':[]},'operator_0']},'range':{'Tbop':[{'sources':[],'sinks':[]},'Oadd',{'Ebop':['Omul',{'Evar':'range_0'},{'Ebop':['Omul',{'Econst':1},{'Econst':-1}]}]},{'Econst':1}]},'request':{'Tdict':{'GET':{'Tdict':{'operator':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':[]},'operator_0']},'range':{'Tvar':[{'sources':[],'sinks':[]},'range_0']}}}}},'result':{'Tconst':[{'sources':[],'sinks':[]},0]},'x':{'Tvar':[{'sources':[],'sinks':[]},'range_0']}},'sp':[{'Tbop':[{'sources':[],'sinks':[]},'Olt',{'Evar':'range_0'},{'Econst':0}]},{'Tbop':[{'sources':[],'sinks':[]},'One',{'Ebop':['Oadd',{'Ebop':['Omul',{'Evar':'range_0'},{'Ebop':['Omul',{'Econst':1},{'Econst':-1}]}]},{'Econst':1}]},{'Econst':0}]}]}},'trace':{'return':{'Tconst':[{'sources':[],'sinks':[]},0]},'state':{'svm':{'operator':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':[]},'operator_0']},'range':{'Tbop':[{'sources':[],'sinks':[]},'Oadd',{'Evar':'range_0'},{'Econst':1}]},'request':{'Tdict':{'GET':{'Tdict':{'operator':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':[]},'operator_0']},'range':{'Tvar':[{'sources':[],'sinks':[]},'range_0']}}}}},'result':{'Tconst':[{'sources':[],'sinks':[]},0]},'x':{'Tvar':[{'sources':[],'sinks':[]},'range_0']}},'sp':[{'Tbop':[{'sources':[],'sinks':[]},'Oge',{'Evar':'range_0'},{'Econst':0}]},{'Tbop':[{'sources':[],'sinks':[]},'One',{'Ebop':['Oadd',{'Evar':'range_0'},{'Econst':1}]},{'Econst':0}]}]}}}");
    ("programs/spai1.py", 4, "{'trace':{'return':{},'state':{'svm':{'__source':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':['CodeExecution']},'joined_0']},'operator':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':[]},'operator_0']},'range':{'Tvar':[{'sources':[],'sinks':[]},'range_0']},'request':{'Tdict':{'GET':{'Tdict':{'operator':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':[]},'operator_0']},'range':{'Tvar':[{'sources':[],'sinks':[]},'range_0']}}}}}},'sp':[{'Tbop':[{'sources':[],'sinks':[]},'Oeq',{'Evar':'range_0'},{'Econst':0}]}]}},'trace':{'return':{'Tconst':[{'sources':[],'sinks':[]},0]},'state':{'svm':{'operator':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':[]},'operator_0']},'range':{'Tvar':[{'sources':[],'sinks':[]},'range_0']},'request':{'Tdict':{'GET':{'Tdict':{'operator':{'Tvar':[{'sources':['CustomUserControlled'],'sinks':[]},'operator_0']},'range':{'Tvar':[{'sources':[],'sinks':[]},'range_0']}}}}},'result':{'Tconst':[{'sources':[],'sinks':[]},0]}},'sp':[{'Tbop':[{'sources':[],'sinks':[]},'One',{'Evar':'range_0'},{'Econst':0}]}]}}}");
    ("programs/functionality_tests/function_calls/local_assignment.py", 1, "{'trace':{'return':{},'state':{'svm':{'x':{'Tvar':[{'sources':['UserControlled'],'sinks':[]},'symb_0']},'y':{'Tconst':[{'sources':[],'sinks':[]},10]}},'sp':[]}}}");
  ]

